In [319]:
# Step 1 import libraries
import numpy as np
import pandas as pd

In [320]:
# Step 2 Load DataSet
df = pd.read_excel(r'C:\Users\VICTUS\OneDrive\Desktop\Customer Churn Analysis\customer_subscription_churn_usage_patterns.xlsx')

In [321]:
# Step 3 First Look
df.head()

,user_id,signup_date,plan_type,Age,monthly_fee,avg_weekly_usage_hours,support_tickets,payment_failures,tenure_months,last_login_days_ago,churn
0,1,2023-04-15,Premium,20.0,-699.0,1.1,4,1.0,8.0,14,Yes
1,2,2023-08-27,Premium,107.0,699.0,2.6,6,0.0,35.0,1,Yes
2,3,2023-10-12,Premium,112.0,699.0,14.3,8,3.0,NaN,14,Yes
3,4,2023-12-11,Basic,41.0,-199.0,14.3,5,2.0,11.0,9,Yes
4,5,2023-02-14,Basic,NaN,199.0,9.8,5,2.0,6.0,38,Yes

In [322]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   user_id                 2800 non-null   int64
 1   signup_date             2800 non-null   datetime64[us]
 2   plan_type               2800 non-null   str
 3   Age                     2798 non-null   float64
 4   monthly_fee             2798 non-null   float64
 5   avg_weekly_usage_hours  2800 non-null   float64
 6   support_tickets         2800 non-null   int64
 7   payment_failures        2799 non-null   float64
 8   tenure_months           2797 non-null   float64
 9   last_login_days_ago     2800 non-null   int64
 10  churn                   2800 non-null   str
dtypes: datetime64[us](1), float64(5), int64(3), str(2)
memory usage: 240.8 KB

In [323]:
df.describe()

,user_id,signup_date,Age,monthly_fee,avg_weekly_usage_hours,support_tickets,payment_failures,tenure_months,last_login_days_ago
count,2800.000000,2800,2798.000000,2798.000000,2800.000000,2800.000000,2799.000000,2797.000000,2800.000000
mean,1400.500000,2024-01-09 16:06:20.571428,79.130808,433.276626,12.890250,3.888214,2.492676,18.621738,30.005000
min,1.000000,2023-01-01 00:00:00,10.000000,-699.000000,0.500000,0.000000,0.000000,1.000000,0.000000
25%,700.750000,2023-07-09 18:00:00,44.000000,199.000000,6.700000,2.000000,1.000000,10.000000,14.000000
50%,1400.500000,2024-01-14 00:00:00,79.000000,399.000000,12.800000,4.000000,2.000000,18.000000,30.000000
75%,2100.250000,2024-07-12 06:00:00,115.000000,699.000000,19.200000,6.000000,4.000000,27.000000,46.000000
max,2800.000000,2024-12-31 00:00:00,150.000000,699.000000,25.000000,8.000000,5.000000,36.000000,60.000000
std,808.434702,NaN,40.976305,207.589876,7.109183,2.606777,1.691293,10.374287,17.852757

In [324]:
df.shape

(2800, 11)

In [325]:
#Step 4 Check For Missing Value
df.isnull().sum()

user_id                   0
signup_date               0
plan_type                 0
Age                       2
monthly_fee               2
avg_weekly_usage_hours    0
support_tickets           0
payment_failures          1
tenure_months             3
last_login_days_ago       0
churn                     0
dtype: int64

In [326]:
# Step 5 Check Duplicate Record
df.duplicated().sum()

np.int64(0)

In [327]:
# Remove Duplicates
df.drop_duplicates(inplace = True)

In [328]:
# Recheck For Duplicate Record
df.duplicated().sum()

np.int64(0)

In [329]:
df.shape

(2800, 11)

In [330]:
# Replace Dirty Values
df.replace(['N/A', 'NULL', '', ' '], np.nan, inplace  = True)

,user_id,signup_date,plan_type,Age,monthly_fee,avg_weekly_usage_hours,support_tickets,payment_failures,tenure_months,last_login_days_ago,churn
0,1,2023-04-15,Premium,20.0,-699.0,1.1,4,1.0,8.0,14,Yes
1,2,2023-08-27,Premium,107.0,699.0,2.6,6,0.0,35.0,1,Yes
2,3,2023-10-12,Premium,112.0,699.0,14.3,8,3.0,NaN,14,Yes
3,4,2023-12-11,Basic,41.0,-199.0,14.3,5,2.0,11.0,9,Yes
4,5,2023-02-14,Basic,NaN,199.0,9.8,5,2.0,6.0,38,Yes
...,...,...,...,...,...,...,...,...,...,...,...
2795,2796,2023-03-10,Standard,61.0,399.0,6.7,1,1.0,21.0,59,No
2796,2797,2024-11-20,Standard,126.0,399.0,11.0,4,0.0,6.0,4,No
2797,2798,2024-08-13,Standard,129.0,399.0,11.0,0,4.0,22.0,59,No
2798,2799,2024-05-23,PREMIUM,13.0,699.0,15.0,3,4.0,25.0,20,No
2799,2800,2024-03-21,Standard,39.0,399.0,2.0,0,1.0,12.0,1,Yes

In [331]:
df.isnull().sum()

user_id                   0
signup_date               0
plan_type                 0
Age                       2
monthly_fee               2
avg_weekly_usage_hours    0
support_tickets           0
payment_failures          1
tenure_months             3
last_login_days_ago       0
churn                     0
dtype: int64

In [332]:
# Step 7 Remove Extra Spaces
df = df.map(lambda x: x.strip() if isinstance(x, str) else x)

In [333]:
#Value Count
df["plan_type"].value_counts()

plan_type
Premium     943
Standard    932
Basic       922
BASIC         1
STANDARD      1
PREMIUM       1
Name: count, dtype: int64

In [334]:
# Step 8 Proper Case
df["plan_type"] = df["plan_type"].str.title()

In [335]:
df["plan_type"].value_counts()

plan_type
Premium     944
Standard    933
Basic       923
Name: count, dtype: int64

In [336]:
# step 9  standardize churn column if until your dataset contain churn column
df['churn'].value_counts()

churn
Yes    1605
No     1195
Name: count, dtype: int64

In [337]:
#Step 10 Convert Numeric Column( if the DataSet Contain numberic value but describe as object)
#cols = ["Age", "Monthly_charge"]

#for c in cols:
    #df[c] = pd.to_numeric(df[c],error = "coerce") # coerce mean set as null

In [338]:
#df.describe()

In [339]:
# Removing invalid Age (If Dataset Contain invaild Age)
df = df[(df ['Age'] >= 18) & (df ['Age'] < 100)]

In [340]:
# Step 11 Removing Negative Value
df = df[df['monthly_fee'] > 0]

In [341]:
# checking the shape of the Data After Removing -ve values
df.shape

(1618, 11)

In [342]:
# Step 12 Change The Date Format

df['signup_date']=pd.to_datetime(df['signup_date'],errors='coerce')

In [343]:
# Step 13 Filling Missing Cells
df["Age"]=df["Age"].fillna(df["Age"].mean())
df["monthly_fee"]=df["monthly_fee"].fillna(df["monthly_fee"].mean())
df["tenure_months"]=df["tenure_months"].fillna(df["tenure_months"].mean())

In [344]:
# Step 14 Feature Enggineering (Creation of New Columns)
# Customer Lifetime Value
df['Customer_Value']=df["monthly_fee"]*df["tenure_months"]

In [345]:
df.head()

,user_id,signup_date,plan_type,Age,monthly_fee,avg_weekly_usage_hours,support_tickets,payment_failures,tenure_months,last_login_days_ago,churn,Customer_Value
5,6,2024-10-05,Premium,37.0,699.0,13.6,6,0.0,30.000000,35,Yes,20970.00000
6,7,2023-10-24,Premium,20.0,699.0,14.6,1,0.0,24.000000,42,Yes,16776.00000
9,10,2024-10-17,Premium,26.0,699.0,13.6,3,1.0,18.972171,29,No,13261.54731
10,11,2023-11-20,Premium,97.0,699.0,5.9,5,NaN,36.000000,14,No,25164.00000
13,14,2023-02-18,Standard,22.0,399.0,9.4,2,4.0,26.000000,31,Yes,10374.00000

In [346]:
# Tenure Groups "0-12" "13-24" "25-48" "49-72"
bins =[0,12,24,48,72]
label = labels=["0-12 months", "13-24 months", "25-48 months", "49-72 months"]
df['tenure_months']=pd.cut(df['tenure_months'], bins = bins, labels = label)

In [347]:
df.head()

,user_id,signup_date,plan_type,Age,monthly_fee,avg_weekly_usage_hours,support_tickets,payment_failures,tenure_months,last_login_days_ago,churn,Customer_Value
5,6,2024-10-05,Premium,37.0,699.0,13.6,6,0.0,25-48 months,35,Yes,20970.00000
6,7,2023-10-24,Premium,20.0,699.0,14.6,1,0.0,13-24 months,42,Yes,16776.00000
9,10,2024-10-17,Premium,26.0,699.0,13.6,3,1.0,13-24 months,29,No,13261.54731
10,11,2023-11-20,Premium,97.0,699.0,5.9,5,NaN,25-48 months,14,No,25164.00000
13,14,2023-02-18,Standard,22.0,399.0,9.4,2,4.0,25-48 months,31,Yes,10374.00000

In [348]:
# Senior Citizen Flags
df["Senior_Flag"]=np.where(df["Age"] >= 60, "Senior","Adult")

In [349]:
df.head()

,user_id,signup_date,plan_type,Age,monthly_fee,avg_weekly_usage_hours,support_tickets,payment_failures,tenure_months,last_login_days_ago,churn,Customer_Value,Senior_Flag
5,6,2024-10-05,Premium,37.0,699.0,13.6,6,0.0,25-48 months,35,Yes,20970.00000,Adult
6,7,2023-10-24,Premium,20.0,699.0,14.6,1,0.0,13-24 months,42,Yes,16776.00000,Adult
9,10,2024-10-17,Premium,26.0,699.0,13.6,3,1.0,13-24 months,29,No,13261.54731,Adult
10,11,2023-11-20,Premium,97.0,699.0,5.9,5,NaN,25-48 months,14,No,25164.00000,Senior
13,14,2023-02-18,Standard,22.0,399.0,9.4,2,4.0,25-48 months,31,Yes,10374.00000,Adult

In [350]:
# Churn Flags
df["Churn_Flag"]=df["churn"].map({"Yes": 1, "No": 0})

In [351]:
df.head()

,user_id,signup_date,plan_type,Age,monthly_fee,avg_weekly_usage_hours,support_tickets,payment_failures,tenure_months,last_login_days_ago,churn,Customer_Value,Senior_Flag,Churn_Flag
5,6,2024-10-05,Premium,37.0,699.0,13.6,6,0.0,25-48 months,35,Yes,20970.00000,Adult,1
6,7,2023-10-24,Premium,20.0,699.0,14.6,1,0.0,13-24 months,42,Yes,16776.00000,Adult,1
9,10,2024-10-17,Premium,26.0,699.0,13.6,3,1.0,13-24 months,29,No,13261.54731,Adult,0
10,11,2023-11-20,Premium,97.0,699.0,5.9,5,NaN,25-48 months,14,No,25164.00000,Senior,0
13,14,2023-02-18,Standard,22.0,399.0,9.4,2,4.0,25-48 months,31,Yes,10374.00000,Adult,1

In [352]:
#Final Check
df.info()

<class 'pandas.DataFrame'>
Index: 1618 entries, 5 to 2799
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   user_id                 1618 non-null   int64
 1   signup_date             1618 non-null   datetime64[us]
 2   plan_type               1618 non-null   str
 3   Age                     1618 non-null   float64
 4   monthly_fee             1618 non-null   float64
 5   avg_weekly_usage_hours  1618 non-null   float64
 6   support_tickets         1618 non-null   int64
 7   payment_failures        1617 non-null   float64
 8   tenure_months           1618 non-null   category
 9   last_login_days_ago     1618 non-null   int64
 10  churn                   1618 non-null   str
 11  Customer_Value          1618 non-null   float64
 12  Senior_Flag             1618 non-null   str
 13  Churn_Flag              1618 non-null   int64
dtypes: category(1), datetime64[us](1), float64(5), int64(4), str(3)
memory usage: 178.6 KB

In [353]:
df.describe()

,user_id,signup_date,Age,monthly_fee,avg_weekly_usage_hours,support_tickets,payment_failures,last_login_days_ago,Customer_Value,Churn_Flag
count,1618.000000,1618,1618.000000,1618.000000,1618.000000,1618.000000,1617.000000,1618.000000,1618.000000,1618.000000
mean,1406.993820,2024-01-10 16:49:14.758961,58.032138,436.021014,12.746848,3.955501,2.463822,29.729295,8283.549782,0.561187
min,6.000000,2023-01-01 00:00:00,18.000000,199.000000,0.500000,0.000000,0.000000,0.000000,199.000000,0.000000
25%,717.250000,2023-07-13 00:00:00,38.000000,199.000000,6.600000,2.000000,1.000000,14.000000,3495.000000,0.000000
50%,1401.000000,2024-01-15 12:00:00,57.000000,399.000000,12.500000,4.000000,2.000000,29.000000,6368.000000,1.000000
75%,2102.750000,2024-07-08 00:00:00,78.000000,699.000000,18.900000,6.000000,4.000000,45.000000,11970.000000,1.000000
max,2800.000000,2024-12-31 00:00:00,99.000000,699.000000,25.000000,8.000000,5.000000,60.000000,25164.000000,1.000000
std,810.861961,NaN,23.688876,205.749818,7.053714,2.626490,1.694512,17.789698,6344.177332,0.496395

In [354]:
df.isnull().sum()

user_id                   0
signup_date               0
plan_type                 0
Age                       0
monthly_fee               0
avg_weekly_usage_hours    0
support_tickets           0
payment_failures          1
tenure_months             0
last_login_days_ago       0
churn                     0
Customer_Value            0
Senior_Flag               0
Churn_Flag                0
dtype: int64

In [355]:
# Step 15 CSV Clean Dataset 
df.to_csv("Clean_Churn_Data.csv", index=False)

In [356]:

from sqlalchemy import create_engine
engine=create_engine("mysql+pymysql://root:MySQL07@localhost/churndb")

In [359]:
# Step 16 Export to MySQL
import urllib.parse
from sqlalchemy import create_engine


raw_password = "MySQL07@"
safe_password = urllib.parse.quote_plus(raw_password)


engine = create_engine(
    f"mysql+pymysql://root:{safe_password}@localhost:3306/churndb"
)

In [358]:
df.to_sql(
    name="customer_churn",
    con=engine,
    if_exists="replace",
    index=False
)

1618